name: flutter_arb_translator
description: A command line tool which simplifies translation of Flutter ARB files.
version: 1.0.24
homepage: https://github.com/sxtfv/flutter_arb_translator

environment:
  sdk: '>=2.16.1 <4.0.0'

dependencies:
   http: ^1.6.0
   path: ^1.9.1
   encrypter_plus: ^5.1.0
   pointycastle: ^4.0.0
   args: ^2.7.0
   crypto: ^3.0.7
   convert: ^3.1.2
   intl: ^0.20.2
   html_unescape: ^2.0.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
